### ISSUE TITLE
Feature request: allow pasting content

### ISSUE THREAD

**Issue by MatzeKitt** [ProxymanApp/Text-Differ#2]
Currently, it’s required to have the content available as files to compare them. I usually just have them in my clipboard and thus it would be very helpful to be able to just paste content into each side of Text Differ in order to compare them instead of being forced to create files first.

**Comment by bomberstudios** [comment]
+1. I used TextMate's "Diff with Clipboard" feature back in the day and I loved it.

**Comment by NghiaTranUIT** [comment]
Thanks, I will add this feature to next release 👍

**Comment by NghiaTranUIT** [comment]
@bomberstudios @MatzeKitt just a friendly reminder that I've pushed new update: https://github.com/ProxymanApp/Text-Differ/releases/tag/1.3

You can simply paste the content to the Diff View 👍

**Comment by bomberstudios** [comment]
Thanks a lot for this!

**Comment by MatzeKitt** [comment]
Wow, that was quick! Thank you! ❤️
