### ISSUE TITLE
Feature request: multiple windows

### ISSUE THREAD

**Issue by addisonjames** [ProxymanApp/Text-Differ#5]
multiple windows would be great. thanks

**Comment by NghiaTranUIT** [comment]
Multiple Windows is ready on [v1.5.0](https://github.com/ProxymanApp/Text-Differ/releases/tag/1.5.0) 👍 

You can simply create new Windows by using Command+N or File -> New.

**Comment by addisonjames** [comment]
Oh cool didn't realize you released and changed the name. Just purchased from App Store and updated from Text Differ 1.2

**Comment by NghiaTranUIT** [comment]
Thanks for your support @addisonjames 🙇
